### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by tenbits** [comment]
Thank you, merged.

**Comment by lildude** [comment]
@tenbits can you update the `mask.tmLanguage` file too to pull in the changes from the YAML file.  The Linguist grammar compiler now prefers the "compiled" grammar over the YAML file.

**Comment by lildude** [comment]
Oh yes, you probably want to make the same change to the JSON-tmLanguage file too, for those that use that file 😉

**Comment by tenbits** [comment]
Thank you @lildude, good point, I have just recompiled the fixed YAML file und pushed a new version.

**Pull request merged**
